admin_panel/urls.py
from admin_panel import views #. mane Current Directory an ai Directory theke Views Ta Import korse
from django.urls import path

# Django Olny looks at Main Url.py

app_name ='admin_panel' #namespacing the URL
urlpatterns = [
   path('admin_home',views.admin_home,name='admin_home'),

   path('doctor_index',views.doctor_index,name='doctor_index'),
   path('doctor_form',views.doctor_form,name='doctor_form'),
   path('doctor_info/<int:doctor_id>/',views.doctor_info,name='doctor_info'),
   path('doctor_update/<int:doctor_id>/',views.doctor_update,name='doctor_update'),
   path('doctor_delete/<int:doctor_id>/',views.doctor_delete,name='doctor_delete'),
   
   
   path('patient_index',views.patient_index,name='patient_index'),
   path('patient_form',views.patient_form,name='patient_form'),
   path('patient_info/<int:patient_id>/',views.patient_info,name='patient_info'),
   path('patient_update/<int:patient_id>/',views.patient_update,name='patient_update'),
   path('patient_delete/<int:patient_id>/',views.patient_delete,name='patient_delete'),

  


] 

doctor/urls.py
from django.urls import path
from doctor import views 

# Django Olny looks at Main Url.py

app_name = "doctor"

urlpatterns = [
   path('doctor_authentication',views.doctor_authentication,name='doctor_authentication'),
   path('doctor_signup',views.doctor_signup,name='doctor_signup'), 
   path('doctor_login',views.doctor_login,name='doctor_login'),     
              ] 

home/urls.py
from django.urls import path
from home import views 

# Django Olny looks at Main Url.py


urlpatterns = [
   path('',views.home,name='home'),
] 

patient/urls.py
from django.urls import path
from .import views 

# Django Olny looks at Main Url.py

#URLS of Patient_Paths
urlpatterns = [
   path('patient_register',views.patient_register,name='patient_register'),
   path('patient_list',views.patient_list,name='patient_list'),  
   path('patient_login',views.patient_login,name='patient_login'),  
   path('patient_logout',views.patient_logout,name='patient_logout'),  
   path('patient_profile/<int:patient_id>',views.patient_profile,name='patient_profile'),  
] 

admin_panel/models.py
from django.db import models


# Create your models here.

doctor/models.py
from django.db import models

# Create your models here.
class Doctor(models.Model):
    doctor_email=models.CharField(max_length=500)
    doctor_password=models.CharField(max_length=500)
    doctor_name=models.CharField(max_length=500)
    doctor_gender=models.CharField(max_length=400)
    doctor_visitng_hour=models.CharField(max_length=400)
    doctor_room_number=models.CharField(max_length=400)

def __str__(self):
    return str(self.pk)+" "+self.doctor_name + " "

patient/models.py
from django.db import models

# Create your models here.

class Patient(models.Model):
    patient_email=models.CharField(max_length=500)
    patient_password=models.CharField(max_length=500)
    patient_name=models.CharField(max_length=500)
    patient_gender=models.CharField(max_length=400)
    patient_age=models.IntegerField()
    patient_phone_number=models.IntegerField()

def __str__(self):
    return str(self.pk)+" "+self.patient_name + " "

admin_panel/forms.py
from django import forms
from doctor import models as doctor_model
from patient import models as patient_model

class DoctorForm(forms.ModelForm): # Ei Class Ta Doctor Table er Jonno Form Create Kortese#
    class Meta:
        model = doctor_model.Doctor
        fields = "__all__"


class PatientForm(forms.ModelForm): # Ei Class Ta Doctor Table er Jonno Form Create Kortese
    class Meta:
        model = patient_model.Patient
        fields = "__all__"

patient/forms.py
from django import forms
from patient import models

class PatientRegisterForm(forms.ModelForm): #It will create the Patient_Registration_Form
   class Meta:
       model = models.Patient
       fields = "__all__"

class PatientLoginForm(forms.ModelForm): #It will create the Patient_Login_Form
    class Meta:
        model = models.Patient
        fields = ['patient_email', 'patient_password']

class PatientLogoutForm(forms.ModelForm): #It will create the Patient_Logout_Form
    class Meta:
        model = models.Patient
        fields = ['patient_email', 'patient_password']

admin_panel/views.py
from django.shortcuts import render
from django.http import HttpResponse
from admin_panel import forms
from doctor.models import Doctor
from patient.models import Patient




def admin_home(request):
    """
    This method is used to display home page of Admin_panel.


    :param request: it's a HttpResponse from user.


    :type request: HttpResponse.


    :return: this method returns a home page of the admin_panel
     which is a HTML page.


    :rtype: HttpResponse.
    """
    diction={'title':"Admin Panel"}
    return render(request, 'admin_panel/admin_home.html',context=diction)



    """
     From Here Managing Doctors part Started.

    """
def doctor_index(request): # It is Viweing Doctor index
    """
     This method is used to display the Doctor list.

     :param request: it's a HttpResponse from user.

     :type request: HttpResponse.

     :return: this method returns a html page that display all the Doctors 
      available.

     :rtype: HttpResponse.
     
     """
    doctor_list = Doctor.objects.order_by('doctor_name')

    diction={'title':"Doctor Management",'doctor_list':doctor_list}
    return render(request, 'admin_panel/doctor_index.html',context=diction)




def doctor_form(request):
    """
     This method is used to Add  Doctor via Form.

     :param request: it's a HttpResponse from user.

     :type request: HttpResponse.

     :return: this method returns a html page that  allows user to add 
     
     Doctors.
    
     :rtype: HttpResponse.
     
     """
    form = forms.DoctorForm() 
    if request.method=="POST":
        form = forms.DoctorForm(request.POST)   
        if form.is_valid(): # Validity Check kore save kore Dibe
            form.save(commit=True)
            return doctor_index(request)
    diction={'title':"Doctor Mangement","doctor_form":form}
    return render(request, 'admin_panel/doctor_form.html',context=diction)



def doctor_info(request,doctor_id):
    """ 
     This method is used to View Indivdual Doctor after getting from their unique 
     primary key.

     :param request: it's a HttpResponse from user and Doctor primary key from the 
      databae.

     :type request: HttpResponse.

     :return: this method returns a html page that display information of an 
     
     individual Doctor.
           
     :rtype: HttpResponse.
     
     """
    doctor_info =Doctor.objects.get(pk=doctor_id)
    diction = {'doctor_info':doctor_info}
    return render(request, 'admin_panel/doctor_info.html',context =diction)




def doctor_update(request,doctor_id):
    """
     This method is used to Update each Doctor according to their  unique primary
     key.

     :param request: it's a HttpResponse from user and Doctor primary key from the 
      databae.

     :type request: HttpResponse.

     :return: this method returns a html page that update information of an 
     
     individual Doctor.
           
     :rtype: HttpResponse.
     
     """
    doctor_info =Doctor.objects.get(pk=doctor_id)
    
    form = forms.DoctorForm(instance=doctor_info)
    if request.method=="POST":
        form=forms.DoctorForm(request.POST,instance=doctor_info)
        if form.is_valid(): 
            form.save(commit=True)
            return doctor_index(request)
    diction = {'doctor_form':form}
    return render(request, 'admin_panel/doctor_update.html',context =diction)




def doctor_delete(request,doctor_id):
    """
     This method is used to Delete each Doctor according to their  unique primary
     key.

     :param request: it's a HttpResponse from user and Doctor primary key from the 
      databae.

     :type request: HttpResponse.

     :return: this method returns a html page that delete information of an 
     
     individual Doctor.
           
     :rtype: HttpResponse.
     
     """
    doctor =Doctor.objects.get(pk=doctor_id).delete()
    diction = {'delete_message': "Delete Done"}
    return render(request, 'admin_panel/doctor_delete.html',context =diction)


"""
     From Here Managing Patients part Started.

"""
def patient_index(request): 
    """
     This method is used to display the Patient list.

     :param request: it's a HttpResponse from user.

     :type request: HttpResponse.

     :return: this method returns a html page that display all the Patients 
      available.

     :rtype: HttpResponse.
     
    """
    patient_list = Patient.objects.order_by('patient_name')
    diction={'title':"Patient Management",'patient_list':patient_list}
    return render(request, 'admin_panel/patient_index.html',context=diction)



def patient_form(request):
    """
     This method is used to Add  Patient via Form.

     :param request: it's a HttpResponse from user.

     :type request: HttpResponse.

     :return: this method returns a html page that  allows user to add 
     
     Patients.
    
     :rtype: HttpResponse.
     
    """
    form = forms.PatientForm()
    if request.method=="POST":
        form = forms.PatientForm(request.POST)
        if form.is_valid(): # Validity Check kore save kore Dibe
            form.save(commit=True)
            return patient_index(request)
    diction={'title':"Patient Mangement","patient_form":form}
    return render(request, 'admin_panel/patient_form.html',context=diction)



def patient_info(request,patient_id):
    """
     This method is used to View Indivdual Patient after getting from their unique 
     primary key.

     :param request: it's a HttpResponse from user and Patient primary key from the 
      databae.

     :type request: HttpResponse.

     :return: this method returns a html page that display information of an 
     
     individual Patient.
           
     :rtype: HttpResponse.
     
    """
    patient_info =Patient.objects.get(pk=patient_id)
    diction = {'patient_info':patient_info}
    return render(request, 'admin_panel/patient_info.html',context =diction)



def patient_update(request,patient_id):
    """
     This method is used to Update each Patient according to their  unique primary
     key.

     :param request: it's a HttpResponse from user and Patient primary key from the 
      databae.

     :type request: HttpResponse.

     :return: this method returns a html page that update information of an 
     
     individual Patient.
           
     :rtype: HttpResponse.
     
    """
    patient_info =Patient.objects.get(pk=patient_id)
    form = forms.PatientForm(instance=patient_info)
    if request.method=="POST":
        form=forms.PatientForm(request.POST,instance=patient_info)
        if form.is_valid():
            form.save(commit=True)
            return patient_index(request)
    diction = {'patient_form':form}
    return render(request, 'admin_panel/patient_update.html',context =diction)





def patient_delete(request,patient_id):
    """
     This method is used to Delete each Patient according to their  unique primary
     key.

     :param request: it's a HttpResponse from user and Patient primary key from the 
      databae.

     :type request: HttpResponse.

     :return: this method returns a html page that delete information of an 
     
     individual Patient.
           
     :rtype: HttpResponse.
     
    """
    patient =Patient.objects.get(pk=patient_id).delete()
    diction = {'delete_message': "Delete Done"}
    return render(request,'admin_panel/patient_delete.html',context =diction)

doctor/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User, auth
from django.http import HttpResponse


def doctor_authentication(request):
    """
    This method is used to show authentacion page.


    :param request: it's a HttpResponse from doctor.


    :type request: HttpResponse.


    :return: this method returns signup and login page after successfully
    submit.


    :rtype: HttpResponse.
    """
    diction = {} 
    return render(request, 'doctor/doctor_authentication.html', context=diction)

def doctor_login(request):
    """
    This method is used to login a doctor.


    :param request: it's a HttpResponse from doctor.


    :type request: HttpResponse.


    :return: this method returns a  login page after successfully
    submit.


    :rtype: HttpResponse.
    """

    if request.method == "POST":
        doctor_name = request.POST['doctor_name']
        doctor_password = request.POST['doctor_password']

        user = auth.authenticate(doctor_name=doctor_name, doctor_password=doctor_password)

        if user is not None:
            auth.login(request, user)
            return render(request, 'doctor/doctor_authentication.html')

    return render(request, 'doctor/doctor_login.html')
    

def doctor_signup(request):    
    """
    This method is used to signup a doctor.


    :param request: it's a HttpResponse from doctor.


    :type request: HttpResponse.


    :return: this method returns a  authentication page after successfull
    registration.
    

    :rtype: HttpResponse.
    """

    if request.method == 'POST':
        doctor_name = request.POST['doctor_name']
        doctor_email = request.POST['doctor_email']
        doctor_password = request.POST['doctor_password']
        doctor_gender = request.POST['doctor_gender']
        doctor_visitng_hour = request.POST['doctor_visitng_hour']
        doctor_room_number = request.POST['doctor_room_number']

        user = User.objects.create_user(doctor_name = doctor_name, doctor_email = doctor_email, doctor_password = doctor_password, doctor_gender = doctor_gender, doctor_visitng_hour = doctor_visitng_hour, doctor_room_number = doctor_room_number)
        user.save()
        print('Successfully Registered')
        return redirect('doctor/doctor_authentication.html')
    else:
        return render(request, 'doctor/doctor_signup.html')




    

patient/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from patient import models
from patient.models import Patient
from patient import forms
from django.contrib.auth.decorators import login_required


# Create your views here.


def patient_register(request):        #Patient_Register

    """
    This method is used to register Patients.
     :param request: it's a HttpResponse from user.
     :type request: HttpResponse.
     :return: this method returns a html page that displays a register form and can submit the form.
     :rtype: HttpResponse.
     
    """
    form= forms.PatientRegisterForm()
    if request.method == 'POST':
        form= forms.PatientRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('patient_login')
    return render(request, 'patient/patient_register.html',{'form':form})
   
def patient_login(request):             #Patient_Login

    """
    This method is used to login Patients.
     :param request: it's a HttpResponse from user.
     :type request: HttpResponse.
     :return: this method returns a html page that displays a login form and can submit the form.
     :rtype: HttpResponse.
     
    """
    form= forms.PatientLoginForm()
    if request.method == 'POST':
        form= forms.PatientLoginForm(request.POST)
        patient_email = request.POST.get('patient_email')
        patient_password = request.POST.get('patient_password')
        return redirect('patient_profile')
        return render(request, 'patient/patient_login.html',{'form':form})

def patient_logout(request):                #Patient_Logout

    """
    This method is used to logout Patients.
     :param request: it's a HttpResponse from user.
     :type request: HttpResponse.
     :return: this method returns a html page that displays home page.
     :rtype: HttpResponse.
     
    """
    form= forms.PatientLogoutForm()
    if request.method == 'POST':
            form= forms.PatientLogoutForm(request.POST)
            patient_email = request.POST.get('patient_email')
            patient_password = request.POST.get('patient_password')
            return redirect('home')
       
def patient_list(request):              #Patient_Lists

    """
    This method is used to show Patient Lists.
     :param request: it's a HttpResponse from user.
     :type request: HttpResponse.
     :return: this method returns a html page that displays Patient Lists.
     :rtype: HttpResponse.
     
    """
    patient_list = Patient.objects.get(pk=patient_id)
    return render (request,'patient/patient_list.html')

@login_required
def patient_profile(request, patient_id):      #Patient_Profile

    """
    This method is used to show Patient Profile.
     :param request: it's a HttpResponse from user.
     :type request: HttpResponse.
     :return: this method returns a html page that displays Patient Profile.
     :rtype: HttpResponse.
     
    """
    patient_profile = Patient.objects.get(pk=patient_id)
    return render (request,'patient/patient_profile.html')
    
    

   
    

admin_panel/templates/admin_panel/admin_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    
    <title>{{ title }}</title> <!Title Ta Dynamically Change hobe>
</head>
<body>
    <ul class="nav">
        <li class="nav-item">
          <a class="nav-link"  href="{% url 'admin_panel:doctor_index' %}">Manage Doctor</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'admin_panel:patient_index' %}">Manage Patient</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Manage Doctor Assistant</a>
        </li>
        
        
      </ul>

    {% block body_block %}

    {% endblock %}
    
</body>
</html>

admin_panel/templates/admin_panel/admin_home.html
{% extends 'admin_panel/admin_base.html' %}

{% block body_block %}

<h3>   Welcome to Admin Panel</h3>

{% endblock body_block %}

admin_panel/templates/admin_panel/doctor_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    
    <title>{{ title }}</title> <!Title Ta Dynamically Change hobe>
</head>
<body>
    <ul class="nav">
        <li class="nav-item">
          <a class="nav-link"  href="{% url 'admin_panel:doctor_index' %}">Index</a>
        </li>
        
        <li class="nav-item">
          <a class="nav-link" href="{% url 'admin_panel:doctor_form' %}">Doctor Form</a>
        </li>
        
      </ul>

    {% block body_block %}

    {% endblock %}
    
</body>
</html>

admin_panel/templates/admin_panel/doctor_delete.html
{% extends 'admin_panel/doctor_base.html' %}

{% block body_block %}

<div class="alert alert-danger">{{delete_message}}</div>


{% endblock body_block %}

admin_panel/templates/admin_panel/doctor_form.html
{% extends 'admin_panel/doctor_base.html' %}

{% block body_block %}

<h3>Doctor Form</h3>

<form action="" method="POST">

    {{ doctor_form.as_p}} <!Form Gula pashapashi na Ashasr Jonno eta korechi>

    {% csrf_token %}
    

    <input type="submit" name="submit" value= "Add Doctor">




</form>

{% endblock body_block %}

admin_panel/templates/admin_panel/doctor_index.html
{% extends 'admin_panel/doctor_base.html' %}

{% block body_block %}

<h3>Manage Doctors</h3>
<ul>
{% if doctor_list %}  <! Doctor List e Kichu Thake>

{% for doctor in doctor_list %}

<a href= "{% url 'admin_panel:doctor_info' doctor_id=doctor.id %}">  <li>{{doctor.doctor_name}}</li></a>

{% endfor %}

{% else %}

<h3>No Doctor</h3>

{% endif %}
</ul>
{% endblock body_block %}

admin_panel/templates/admin_panel/doctor_info.html
{% extends 'admin_panel/doctor_base.html' %}

{% block body_block %}

<h1>Doctor Information</h1>

<h4>Doctor Name: {{doctor_info.doctor_name}}</h4>
<h4>Doctor Email: {{doctor_info.doctor_email}}</h4>
<h4>Doctor Password: {{doctor_info.doctor_password}}</h4>
<h4>Doctor Gender: {{doctor_info.doctor_gender}}</h4>
<h4>Doctor Visiting Hour: {{doctor_info.doctor_visitng_hour}}</h4>
<h4>Doctor Room Number: {{doctor_info.doctor_room_number}}</h4>

<a href="{% url 'admin_panel:doctor_update' doctor_id=doctor_info.id %}" class="btn btn-primary">Update</a>
<a href="{% url 'admin_panel:doctor_delete' doctor_id=doctor_info.id %}" class="btn btn-primary">Delete</a>

{% endblock body_block %}

admin_panel/templates/admin_panel/doctor_update.html
{% extends 'admin_panel/doctor_base.html' %}

{% block body_block %}

<h1>Doctor Update</h1>

<form action="" method="POST">

    {{doctor_form.as_p}}
    {% csrf_token %}

    <input type="submit" value="update">

</form>

{% endblock body_block %}

admin_panel/templates/admin_panel/patient_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    
    <title>{{ title }}</title> <!Title Ta Dynamically Change hobe>
</head>
<body>
    <ul class="nav">
        <li class="nav-item">
          <a class="nav-link"  href="{% url 'admin_panel:patient_index' %}">Index</a>
        </li>
        
        <li class="nav-item">
          <a class="nav-link" href="{% url 'admin_panel:patient_form' %}">Patient Form</a>
        </li>
        
      </ul>

    {% block body_block %}

    {% endblock %}
    
</body>
</html>

admin_panel/templates/admin_panel/patient_delete.html
{% extends 'admin_panel/patient_base.html' %}

{% block body_block %}

<div class="alert alert-danger">{{delete_message}}</div>

{% endblock body_block %}

admin_panel/templates/admin_panel/patient_form.html
{% extends 'admin_panel/patient_base.html' %}

{% block body_block %}

<h3>Patient Form</h3>

<form action="" method="POST">

    {{ patient_form.as_p}} <!Form Gula pashapashi na Ashasr Jonno eta korechi>
    {% csrf_token %}

    <input type="submit" name="submit" value= "Add Patient">




</form>

{% endblock body_block %}

admin_panel/templates/admin_panel/patient_index.html
{% extends 'admin_panel/patient_base.html' %}

{% block body_block %}

<h3>Mange Patients</h3>

<ul>
{% if patient_list %}  <! Doctor List e Kichu Thake>
    
{% for patient in patient_list %}
    
<a href= "{% url 'admin_panel:patient_info' patient_id=patient.id %}"><li>{{patient.patient_name}}</li></a>


    
{% endfor %}
    
{% else %}
    
<h3>No Patient</h3>
    
{% endif %}
</ul>



{% endblock body_block %}

admin_panel/templates/admin_panel/patient_info.html
{% extends 'admin_panel/patient_base.html' %}

{% block body_block %}

<h1>Patient Information</h1>

<h4>Patient Name: {{patient_info.patient_name}}</h4>

<h4>Patient Email: {{patient_info.patient_email}}</h4>
<h4>Patient Password: {{patient_info.patient_password}}</h4>
<h4>Patient Gender: {{patient_info.patient_gender}}</h4>
<h4>Patient Age: {{patient_info.patient_age}}</h4>
<h4>Patient Phone Number: {{patient_info.patient_phone_number}}</h4>

<a href="{% url 'admin_panel:patient_update' patient_id=patient_info.id %}" class="btn btn-primary">Update</a>
<a href="{% url 'admin_panel:patient_delete' patient_id=patient_info.id %}" class="btn btn-primary">Delete</a>


{% endblock body_block %}

admin_panel/templates/admin_panel/patient_update.html
{% extends 'admin_panel/patient_base.html' %}

{% block body_block %}

<h1>Patient Update</h1>

<form action="" method="POST">

    {{patient_form.as_p}}
    {% csrf_token %}

    <input type="submit" value="update">

</form>

{% endblock body_block %}