HospitalManagement/urls.py
from django.contrib import admin
from django.urls import path,path
from django.conf.urls import include



urlpatterns = [
    path('',include('home.urls')),
    # Admin Panel realted path
    path('',include('admin_panel.urls')),
    
    path('admin/', admin.site.urls),
    path('appointment/',include('appointment.urls')),
    path('doctor/',include('doctor.urls')),
    path('doctorassistant/',include('doctor_assistant.urls')),
    path('emergencyservice/',include('emergency_service.urls')),
    path('patient/',include('patient.urls')),

]

admin_panel/urls.py
from admin_panel import views #. mane Current Directory an ai Directory theke Views Ta Import korse
from django.urls import path

# Django Olny looks at Main Url.py

app_name ='admin_panel' #namespacing the URL
urlpatterns = [
   path('admin_home',views.admin_home,name='admin_home'),

   path('doctor_index',views.doctor_index,name='doctor_index'),
   path('doctor_form',views.doctor_form,name='doctor_form'),
   path('doctor_info/<int:doctor_id>/',views.doctor_info,name='doctor_info'),
   path('doctor_update/<int:doctor_id>/',views.doctor_update,name='doctor_update'),
   path('doctor_delete/<int:doctor_id>/',views.doctor_delete,name='doctor_delete'),
   
   
   path('patient_index',views.patient_index,name='patient_index'),
   path('patient_form',views.patient_form,name='patient_form'),
   path('patient_info/<int:patient_id>/',views.patient_info,name='patient_info'),
   path('patient_update/<int:patient_id>/',views.patient_update,name='patient_update'),
   path('patient_delete/<int:patient_id>/',views.patient_delete,name='patient_delete'),

  


] 

doctor/urls.py
from django.urls import path
from doctor import views 

# Django Olny looks at Main Url.py

app_name = "doctor"

urlpatterns = [
   path('doctor_authentication',views.doctor_authentication,name='doctor_authentication'),
   path('doctor_signup',views.doctor_signup,name='doctor_signup'), 
   path('doctor_login',views.doctor_login,name='doctor_login'),     
              ] 

home/urls.py
from django.urls import path
from home import views 

# Django Olny looks at Main Url.py


urlpatterns = [
   path('',views.home,name='home'),
] 

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.

def home(request):
    """
    This method is used to display home page.


    :param request: it's a HttpResponse from user.


    :type request: HttpResponse.


    :return: this method returns a home page
     which is a HTML page.


    :rtype: HttpResponse.
    """
    diction={'title':"Hospital Mangement"}
    return render(request, 'home/home.html',context=diction)

home/templates/home/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    
    <title>{{ title }}</title> <!Title Ta Dynamically Change hobe>
</head>
<body>
    <ul class="nav">
        <li class="nav-item">
          <a class="nav-link"  href="{% url 'admin_panel:admin_home' %}">Admin Panel</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'patient_list' %}">Patient</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'doctor:doctor_authentication' %}">Doctor</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Doctor_Assistant</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Emergency Service</a>
        </li>
        <li class="nav-item">
          <a href="{% url 'patient_register' %}">Patient Register</a>
      </li>
      {% if user.is_authenticated %}
      <a href="{% url 'patient_login' %}">Patient Login</a>
      <a href="{% url 'patient_logout' %}">Logout</a> {% endif %}
        
      </ul>

    {% block body_block %}

    {% endblock %}
    
</body>
</html>

home/templates/home/home.html
{% extends 'home/base.html' %}

{% block body_block %}

<h3>   Welcome to Hospital mangement System</h3>

{% endblock body_block %}