HospitalManagement/urls.py
from django.contrib import admin
from django.urls import path,path
from django.conf.urls import include



urlpatterns = [
    path('',include('home.urls')),
    # Admin Panel realted path
    path('',include('admin_panel.urls')),
    
    path('admin/', admin.site.urls),
    path('appointment/',include('appointment.urls')),
    path('doctor/',include('doctor.urls')),
    path('doctorassistant/',include('doctor_assistant.urls')),
    path('emergencyservice/',include('emergency_service.urls')),
    path('patient/',include('patient.urls')),

]

doctor/urls.py
from django.urls import path
from doctor import views 

# Django Olny looks at Main Url.py

app_name = "doctor"

urlpatterns = [
   path('doctor_authentication',views.doctor_authentication,name='doctor_authentication'),
   path('doctor_signup',views.doctor_signup,name='doctor_signup'), 
   path('doctor_login',views.doctor_login,name='doctor_login'),     
              ] 

home/urls.py
from django.urls import path
from home import views 

# Django Olny looks at Main Url.py


urlpatterns = [
   path('',views.home,name='home'),
] 

doctor/models.py
from django.db import models

# Create your models here.
class Doctor(models.Model):
    doctor_email=models.CharField(max_length=500)
    doctor_password=models.CharField(max_length=500)
    doctor_name=models.CharField(max_length=500)
    doctor_gender=models.CharField(max_length=400)
    doctor_visitng_hour=models.CharField(max_length=400)
    doctor_room_number=models.CharField(max_length=400)

def __str__(self):
    return str(self.pk)+" "+self.doctor_name + " "

doctor/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User, auth
from django.http import HttpResponse


def doctor_authentication(request):
    """
    This method is used to show authentacion page.


    :param request: it's a HttpResponse from doctor.


    :type request: HttpResponse.


    :return: this method returns signup and login page after successfully
    submit.


    :rtype: HttpResponse.
    """
    diction = {} 
    return render(request, 'doctor/doctor_authentication.html', context=diction)

def doctor_login(request):
    """
    This method is used to login a doctor.


    :param request: it's a HttpResponse from doctor.


    :type request: HttpResponse.


    :return: this method returns a  login page after successfully
    submit.


    :rtype: HttpResponse.
    """

    if request.method == "POST":
        doctor_name = request.POST['doctor_name']
        doctor_password = request.POST['doctor_password']

        user = auth.authenticate(doctor_name=doctor_name, doctor_password=doctor_password)

        if user is not None:
            auth.login(request, user)
            return render(request, 'doctor/doctor_authentication.html')

    return render(request, 'doctor/doctor_login.html')
    

def doctor_signup(request):    
    """
    This method is used to signup a doctor.


    :param request: it's a HttpResponse from doctor.


    :type request: HttpResponse.


    :return: this method returns a  authentication page after successfull
    registration.
    

    :rtype: HttpResponse.
    """

    if request.method == 'POST':
        doctor_name = request.POST['doctor_name']
        doctor_email = request.POST['doctor_email']
        doctor_password = request.POST['doctor_password']
        doctor_gender = request.POST['doctor_gender']
        doctor_visitng_hour = request.POST['doctor_visitng_hour']
        doctor_room_number = request.POST['doctor_room_number']

        user = User.objects.create_user(doctor_name = doctor_name, doctor_email = doctor_email, doctor_password = doctor_password, doctor_gender = doctor_gender, doctor_visitng_hour = doctor_visitng_hour, doctor_room_number = doctor_room_number)
        user.save()
        print('Successfully Registered')
        return redirect('doctor/doctor_authentication.html')
    else:
        return render(request, 'doctor/doctor_signup.html')




    

doctor/templates/doctor/doctor_authentication.html
{% extends 'Doctor/doctor_base.html' %}


{% block body_block %}

<h3>Ever Green Hospital Doctor Portal</h3>

{% endblock %}

doctor/templates/doctor/doctor_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    
    <title>{{ title }}</title> 
</head>
<body>
    <ul class="nav">
        
        <li class="nav-item">
          <a class="nav-link" href="{% url 'doctor:doctor_signup' %}">Doctor Signup</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'doctor:doctor_login' %}">Doctor Login</a>
        </li>
        
      </ul>

    {% block body_block %}

    {% endblock %}
    
</body>
</html>

doctor/templates/doctor/doctor_login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <h1>Login</h1>
</head>
<body>
    <form action="doctor_login" method="POST">
        {% csrf_token %}

        <input type="text" name="doctor_name" placeholder="doctor_name"><br>
        <input type="password" name="doctor_password" placeholder="doctor_password"><br>
        <input type="submit">

    </form>
    
</body>
</html>

doctor/templates/doctor/doctor_signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <h1>Ever Green Hospital</h1>
    <h3>Signup Form</h3>
</head>
<body>
    <form action="doctor_signup" method="POST">
        {% csrf_token %}

        <input type="text" name="doctor_name" placeholder="doctor_name"><br>
        <input type="email" name="doctor_email" placeholder="doctor_email"><br>
        <input type="password" name="doctor_password" placeholder="doctor_password"><br>
        <input type="text" name="doctor_gender" placeholder="doctor_gender"><br>
        <input type="text" name="doctor_visitng_hour" placeholder="doctor_visitng_hour"><br>
        <input type="text" name="doctor_room_number" placeholder="doctor_room_number"><br>
        <input type="submit">

    </form>
</body>
</html>